name: 'data_flow_dbt'
version: '1.0.0'
config-version: 2
profile: 'data_flow_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["exposures"]
exposures-paths: ["exposures"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ log('Starting dbt run for ' ~ target.name ~ ' environment', info=True) }}"

on-run-end:
  - "{{ summarize_run_artifacts(results) }}"

vars:
  invalid_activity_label: 0
  source_loaded_at_field: 'ingested_at'
  incremental_start_time: "date_trunc('day', current_timestamp) - interval '1 day'"

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_utils', 'dbt']

models:
  data_flow_dbt:
    +persist_docs: {relation: true, columns: true}
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
    +tags: ['data-flow']

seeds:
  data_flow_dbt:
    +quote_columns: false

snapshots:
  data_flow_dbt:
    +target_schema: "{{ target.schema }}"
    +target_database: "{{ target.database }}"

tests:
  data_flow_dbt:
    +store_failures: true
