services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform_cli_container
    working_dir: /work/terraform
    volumes:
      - ../:/work # プロジェクトルートをコンテナの /work にマウント
      - ~/.aws:/root/.aws
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
    entrypoint: ""
    command: tail -f /dev/null
