data_flow_dbt:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: "{{ var('S3_STAGING_DIR') }}"
      s3_data_dir: "{{ var('S3_DATA_DIR') }}"
      region_name: "{{ var('AWS_REGION') }}"
      database: "{{ var('GLUE_DATABASE') }}"
      schema: "mhealth"
      
      threads: 4
      work_group: "{{ var('ATHENA_WORK_GROUP') }}"
