name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'download_and_upload/**'
      - 'convert_log_to_parquet/**'
      - 'layer/**'
      - 'build.sh'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::143944071087:role/GitHubActionsTerraformDeployRole
          aws-region: ap-northeast-1

      - name: Build Lambda Deployment Packages
        run: bash build.sh

      - name: Build and Run Terraform
        run: |
          cd terraform
          docker compose build
          docker compose run --rm terraform-cli bash -c "terraform init && terraform workspace select prod || terraform workspace new prod && terraform apply -auto-approve -var-file=prod.tfvars"
